from __future__ import annotations

import re
from pathlib import Path
from typing import Any

import yaml

from guideline_skill.schema import (
    DiseaseSkillPack,
    RecommendationCard,
    RoutingProfile,
    SubSkill,
    validate_skill_pack,
)
from pdf_guideline_parser import GuidelineSection, parse_guideline_sections, save_sections_json


RECOMMENDATION_PATTERN = re.compile(
    r"推荐意见\s*(?P<number>\d+)\s*[:：]?\s*(?P<body>.*?)(?=(?:推荐意见\s*\d+\s*[:：]?)|\Z)",
    re.S,
)


def extract_recommendation_cards_from_sections(
    sections: list[GuidelineSection],
    *,
    disease_name: str,
    guideline_name: str,
    guideline_version: str,
) -> list[RecommendationCard]:
    cards: list[RecommendationCard] = []
    recommendation_id_counts: dict[str, int] = {}
    for section in sections:
        for match in RECOMMENDATION_PATTERN.finditer(section.text):
            number = match.group("number")
            raw_body = _clean_recommendation_text(match.group("body"))
            if not raw_body:
                continue
            recommendation_text = extract_recommendation_statement(raw_body)
            evidence_level = extract_evidence_level(raw_body)
            recommendation_strength = extract_recommendation_strength(raw_body)
            rationale = extract_rationale(raw_body, recommendation_text)
            source_span = _source_span(
                section=section,
                number=number,
                raw_body=raw_body,
            )
            cards.append(
                RecommendationCard(
                    recommendation_id=_unique_draft_recommendation_id(
                        number,
                        recommendation_id_counts,
                    ),
                    source_section=section.title,
                    source_section_cn=section.title,
                    clinical_stage=infer_clinical_stage(section.title, recommendation_text),
                    clinical_task=infer_clinical_task(section.title, recommendation_text),
                    population=f"Patients relevant to {disease_name}",
                    condition=infer_condition(recommendation_text),
                    action=recommendation_text,
                    evidence_level=evidence_level,
                    recommendation_strength=recommendation_strength,
                    rationale=rationale,
                    required_inputs=infer_required_inputs(recommendation_text),
                    safety_notes=[
                        "Draft extracted automatically; requires clinician/editor human review before use.",
                        "Do not use this draft card as final medical advice.",
                    ],
                    source_span=source_span,
                    source_quote=recommendation_text,
                    page=section.page_start,
                    review_status="needs_human_review",
                )
            )
    return cards


def extract_recommendations_from_pdf(
    *,
    pdf_path: str | Path,
    disease_name: str,
    guideline_name: str,
    guideline_version: str,
    output_path: str | Path,
    sections_output_path: str | Path | None = None,
) -> DiseaseSkillPack:
    sections = parse_guideline_sections(pdf_path)
    cards = extract_recommendation_cards_from_sections(
        sections,
        disease_name=disease_name,
        guideline_name=guideline_name,
        guideline_version=guideline_version,
    )
    draft_pack = build_draft_skill_pack(
        pdf_path=pdf_path,
        disease_name=disease_name,
        guideline_name=guideline_name,
        guideline_version=guideline_version,
        recommendation_cards=cards,
    )
    save_draft_skill_pack(draft_pack, output_path)
    save_sections_json(
        sections,
        sections_output_path or Path(output_path).with_name("extracted_sections.json"),
    )
    return draft_pack


def build_draft_skill_pack(
    *,
    pdf_path: str | Path,
    disease_name: str,
    guideline_name: str,
    guideline_version: str,
    recommendation_cards: list[RecommendationCard],
) -> DiseaseSkillPack:
    if not recommendation_cards:
        raise ValueError("No recommendation cards were extracted from the guideline text.")
    skill_name = _slugify(f"{disease_name}_{guideline_version}_draft")
    recommendation_ids = [card.recommendation_id for card in recommendation_cards]
    return validate_skill_pack(
        DiseaseSkillPack(
            skill_name=skill_name,
            disease_name=disease_name,
            disease_aliases=[disease_name],
            guideline_name=guideline_name,
            guideline_version=guideline_version,
            source_pdf=str(pdf_path),
            target_users=["human guideline reviewer", "clinical knowledge engineer"],
            scope="Draft skill pack generated by semi-automatic PDF extraction; all cards require human review.",
            routing_profile=RoutingProfile(
                body_system="unknown",
                key_symptoms=[],
                key_tests=[],
                key_findings=[],
                red_flags=[],
                must_differentiate=["to_be_reviewed"],
                disease_aliases=[disease_name],
            ),
            subskills=[
                SubSkill(
                    subskill_id="draft_recommendation_review",
                    name="Draft recommendation review",
                    description="Holds automatically extracted draft recommendation cards for human review.",
                    clinical_tasks=["human review"],
                    required_inputs=["source_pdf", "guideline_text"],
                    recommendation_ids=recommendation_ids,
                    output_fields=["recommendation_cards", "source_references", "safety_warnings"],
                )
            ],
            recommendation_cards=recommendation_cards,
            safety_constraints=[
                "Draft cards must not output a final diagnosis.",
                "Draft cards must not be used for treatment advice until human review is complete.",
                "Information-insufficient cases require missing information and safety warnings.",
            ],
        )
    )


def save_draft_skill_pack(skill_pack: DiseaseSkillPack, path: str | Path) -> None:
    output_path = Path(path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        yaml.safe_dump(
            skill_pack.model_dump(mode="json", exclude_none=True),
            allow_unicode=True,
            sort_keys=False,
        ),
        encoding="utf-8",
    )


def extract_recommendation_statement(raw_body: str) -> str:
    text = re.sub(r"[（(]\s*(?:证据等级|證據等級|推荐强度|推薦強度|BPS).*", "", raw_body, flags=re.S)
    text = re.split(r"(?:推荐理由|推薦理由|理由|实施建议|實施建議|说明|注[:：])", text, maxsplit=1)[0]
    return _clean_recommendation_text(text)


def extract_evidence_level(raw_body: str) -> str:
    patterns = (
        r"证据等级\s*[:：]?\s*([A-Za-z0-9+\-ⅠⅡⅢⅣ一二三四]+)",
        r"證據等級\s*[:：]?\s*([A-Za-z0-9+\-ⅠⅡⅢⅣ一二三四]+)",
        r"Evidence\s*(?:level|Level)?\s*[:：]?\s*([A-Za-z0-9+\-]+)",
    )
    for pattern in patterns:
        match = re.search(pattern, raw_body, re.I)
        if match:
            return match.group(1).strip()
    if re.search(r"\bBPS\b", raw_body, re.I):
        return "BPS"
    return "not_extracted"


def extract_recommendation_strength(raw_body: str) -> str:
    patterns = (
        r"推荐强度\s*[:：]?\s*(强|弱|中等|推荐|不推荐|[A-Za-z0-9+\-]+)",
        r"推薦強度\s*[:：]?\s*(強|弱|中等|推薦|不推薦|[A-Za-z0-9+\-]+)",
        r"Strength\s*[:：]?\s*([A-Za-z0-9+\-]+)",
    )
    for pattern in patterns:
        match = re.search(pattern, raw_body, re.I)
        if match:
            return match.group(1).strip()
    if re.search(r"\bBPS\b", raw_body, re.I):
        return "BPS"
    return "not_extracted"


def extract_rationale(raw_body: str, recommendation_text: str) -> str:
    rationale_match = re.search(
        r"(?:推荐理由|推薦理由|理由|实施建议|實施建議|说明)\s*[:：]?\s*(.+)",
        raw_body,
        re.S,
    )
    if rationale_match:
        return _clean_recommendation_text(rationale_match.group(1))
    remainder = raw_body.replace(recommendation_text, "", 1)
    remainder = re.sub(r"[（(]\s*(?:证据等级|證據等級|推荐强度|推薦強度).*?[）)]", "", remainder, flags=re.S)
    cleaned = _clean_recommendation_text(remainder)
    return cleaned or "needs_human_review"


def infer_clinical_task(section_title: str, recommendation_text: str) -> str:
    text = f"{section_title} {recommendation_text}"
    task_keywords = [
        ("differential diagnosis", ("鉴别", "排除")),
        ("diagnostic workup", ("诊断", "拟诊", "疑诊", "检查", "内镜", "影像", "病理")),
        ("treatment", ("治疗", "诱导", "维持", "手术", "药物")),
        ("monitoring", ("监测", "随访", "复查", "评估")),
        ("nutrition and mental health", ("营养", "精神", "心理")),
    ]
    for task, keywords in task_keywords:
        if any(keyword in text for keyword in keywords):
            return task
    return "needs_human_review"


def infer_clinical_stage(section_title: str, recommendation_text: str) -> str:
    text = f"{section_title} {recommendation_text}"
    stage_keywords = [
        ("emergency_triage", ("急诊", "危重", "穿孔", "梗阻", "大出血", "休克")),
        ("differential_diagnosis", ("鉴别", "排除", "肠结核", "感染性肠炎")),
        ("extent_and_complication_assessment", ("范围", "并发症", "狭窄", "瘘", "脓肿", "肛周", "活动度")),
        ("treatment_selection", ("治疗方案", "诱导", "维持", "药物", "生物制剂", "手术")),
        ("followup_monitoring", ("监测", "随访", "复查", "营养", "心理")),
        ("diagnostic_workup", ("诊断", "拟诊", "疑诊", "检查", "内镜", "影像", "病理", "活检")),
    ]
    for stage, keywords in stage_keywords:
        if any(keyword in text for keyword in keywords):
            return stage
    return "initial_screening"


def infer_condition(recommendation_text: str) -> str:
    match = re.search(r"(?:对于|对|若|如|当|疑诊|拟诊)([^，。；;]{2,80})", recommendation_text)
    if match:
        return _clean_recommendation_text(match.group(0))
    return "needs_human_review"


def infer_required_inputs(recommendation_text: str) -> list[str]:
    mapping = [
        ("symptoms", ("临床", "症状", "表现")),
        ("labs", ("实验室", "血清", "炎性指标", "CRP", "ESR")),
        ("fecal_calprotectin", ("FC", "粪便钙卫蛋白", "钙卫蛋白")),
        ("imaging", ("影像", "CTE", "MRE", "MRI", "超声")),
        ("endoscopy", ("内镜", "肠镜", "结肠镜", "胃十二指肠镜", "胶囊内镜")),
        ("pathology", ("病理", "活检", "组织学")),
        ("differential_diagnosis_review", ("排除", "鉴别")),
        ("safety_risk_assessment", ("风险", "滞留", "狭窄", "禁忌")),
    ]
    inputs = [
        required_input
        for required_input, keywords in mapping
        if any(keyword in recommendation_text for keyword in keywords)
    ]
    return inputs or ["needs_human_review"]


def _source_span(section: GuidelineSection, number: str, raw_body: str) -> str:
    snippet = _clean_recommendation_text(raw_body)
    if len(snippet) > 280:
        snippet = snippet[:277] + "..."
    return (
        f"pages {section.page_start}-{section.page_end}; "
        f"section: {section.title}; recommendation: {number}; "
        f"snippet: {snippet}"
    )


def _unique_draft_recommendation_id(
    recommendation_number: str,
    counts: dict[str, int],
) -> str:
    base_id = f"DRAFT-REC-{int(recommendation_number):03d}"
    counts[base_id] = counts.get(base_id, 0) + 1
    if counts[base_id] == 1:
        return base_id
    return f"{base_id}-{counts[base_id]:03d}"


def _clean_recommendation_text(text: str) -> str:
    text = re.sub(r"\s+", " ", text)
    text = text.strip(" \n\t|。；;")
    return text


def _slugify(text: str) -> str:
    slug = re.sub(r"[^A-Za-z0-9]+", "_", text).strip("_").lower()
    return slug or "draft_guideline_skill_pack"
